# Generated by Django 4.2.5 on 2023-09-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_post_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auther',
            new_name='author',
        ),
    ]
